export const products = [
  {
    name: "Apple iPhone 12",
    priceNow: "18,500 EGP",
    priceOld: "20,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    description: "iPhone 12 in excellent condition, battery 90%",
    status: "Used",
    vendor: "iStore Egypt",
    vendorLink: "#",
    link: "#",
    warrantyText: "30-day warranty",
    insuranceText: "Option to add 1-year warranty",
    
  },
  {
    name: "Samsung Galaxy S22",
    priceNow: "22,000 EGP",
    priceOld: "24,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-5g-1.jpg",
    description: "Galaxy S22 brand new with original box",
    status: "New",
    vendor: "Samsung Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
  },
    {
    name: "Google Pixel 6",
    priceNow: "15,000 EGP",
    priceOld: "17,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-6-1.jpg",
    description: "Pure Android with amazing camera",
    status: "Used",
    vendor: "Pixel Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "30-day warranty",
    insuranceText: "No additional warranty available",
  },
  {
    name: "Xiaomi Redmi Note 11",
    priceNow: "7,500 EGP",
    priceOld: "8,500 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-11-4g-1.jpg",
    description: "Budget phone with 5000mAh battery",
    status: "New",
    vendor: "Xiaomi Shop",
    vendorLink: "#",
    link: "#",
    warrantyText: "6-month warranty",
    insuranceText: "Option to add 1-year warranty",

  },
  {
    name: "Huawei P30 Pro",
    priceNow: "9,000 EGP",
    priceOld: "10,500 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-p30-pro-1.jpg",
    description: "OLED display and powerful 40MP camera",
    status: "Used",
    vendor: "Huawei Egypt",
    vendorLink: "#",
    link: "#",
    warrantyText: "30-day warranty",
    insuranceText: "No additional warranty available",
   
  },
  {
    name: "Oppo Reno 7",
    priceNow: "11,000 EGP",
    priceOld: "12,500 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/oppo/oppo-reno7-1.jpg",
    description: "Great performance with elegant design",
    status: "New",
    vendor: "Oppo Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
    {
    name: "Google Pixel 6",
    priceNow: "15,000 EGP",
    priceOld: "17,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-6-1.jpg",
    description: "Pure Android with amazing camera",
    status: "Used",
    vendor: "Pixel Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "30-day warranty",
    insuranceText: "No additional warranty available",
   
  },
    {
    name: "Samsung Galaxy S22",
    priceNow: "22,000 EGP",
    priceOld: "24,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-5g-1.jpg",
    description: "Galaxy S22 brand new with original box",
    status: "New",
    vendor: "Samsung Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
  {
    name: "Realme GT Master",
    priceNow: "10,500 EGP",
    priceOld: "12,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/realme/realme-gt-master-1.jpg",
    description: "Snapdragon 778G processor with fast performance",
    status: "New",
    vendor: "Realme Egypt",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
    {
    name: "Google Pixel 6",
    priceNow: "15,000 EGP",
    priceOld: "17,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-6-1.jpg",
    description: "Pure Android with amazing camera",
    status: "Used",
    vendor: "Pixel Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "30-day warranty",
    insuranceText: "No additional warranty available",
   
  },

  {
    name: "Infinix Note 12",
    priceNow: "6,200 EGP",
    priceOld: "7,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/infinix/infinix-note12-1.jpg",
    description: "Budget phone with AMOLED display",
    status: "New",
    vendor: "Infinix Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "6-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
  {
    name: "Google Pixel 6",
    priceNow: "15,000 EGP",
    priceOld: "17,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-6-1.jpg",
    description: "Pure Android with amazing camera",
    status: "Used",
    vendor: "Pixel Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "30-day warranty",
    insuranceText: "No additional warranty available",
   
  },
  {
    name: "OnePlus 9",
    priceNow: "14,000 EGP",
    priceOld: "16,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-9-1.jpg",
    description: "Hasselblad camera, smooth performance",
    status: "Used",
    vendor: "OnePlus Egypt",
    vendorLink: "#",
    link: "#",
    warrantyText: "30-day warranty",
    insuranceText: "Optional 1-year warranty",
   
  },
  {
    name: "Motorola Edge 30",
    priceNow: "12,500 EGP",
    priceOld: "14,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/motorola/motorola-edge-30-1.jpg",
    description: "Slim phone with 144Hz OLED display",
    status: "New",
    vendor: "Motorola Egypt",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
  {
    name: "Nokia X30",
    priceNow: "10,000 EGP",
    priceOld: "11,500 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/nokia/nokia-x30-1.jpg",
    description: "Eco-friendly build with AMOLED display",
    status: "New",
    vendor: "Nokia Egypt",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
  {
    name: "Vivo V23",
    priceNow: "9,800 EGP",
    priceOld: "11,200 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/vivo/vivo-v23-1.jpg",
    description: "Slim design with 50MP dual selfie cameras",
    status: "New",
    vendor: "Vivo Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
  {
    name: "Tecno Camon 20",
    priceNow: "7,200 EGP",
    priceOld: "8,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/tecno/tecno-camon-20-1.jpg",
    description: "Affordable smartphone with AMOLED screen",
    status: "New",
    vendor: "Tecno Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "6-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
  {
    name: "Sony Xperia 10 IV",
    priceNow: "13,200 EGP",
    priceOld: "14,500 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/sony/sony-xperia-10-iv-1.jpg",
    description: "Compact phone with long battery life",
    status: "New",
    vendor: "Sony Egypt",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Optional 1-year warranty",
   
  },
  {
    name: "Asus Zenfone 9",
    priceNow: "16,500 EGP",
    priceOld: "18,000 EGP",
    image: "https://fdn2.gsmarena.com/vv/pics/asus/asus-zenfone9-1.jpg",
    description: "Compact flagship with Snapdragon 8+ Gen 1",
    status: "New",
    vendor: "Asus Store",
    vendorLink: "#",
    link: "#",
    warrantyText: "12-month warranty",
    insuranceText: "Option to add 1-year warranty",
   
  },
];
