// Filter groups configuration and constants

export const FILTER_GROUPS = {
  Brands: [
    "Apple",
    "Oppo",
    "Realme",
    "Samsung",
    "Hwawei",
    "Honor",
    "Xiaomi",
    "Infinix",
    "Nokia",
    "Lenovo",
    "Vivo",
    "Oneplus",
    "itel",
    "Google",
    "ZTE",
    "Nothing",
    "Motorola",
  ],
  Type: ["New", "Used"],
  "Sim Card": ["1 sim", "2-sim", "1 sim + e sim"],
  Ram: [
    "3 GB",
    "4 GB",
    "6 GB",
    "8 GB",
    "12 GB",
    "16 GB",
    "36 GB",
    "48 GB",
    "64 GB",
  ],
  Storage: ["32 GB", "64 GB", "128 GB", "256 GB", "512 GB", "1 TB"],
  SSD: ["128 GB", "256 GB", "512 GB", "1 TB"],
  Color: [
    "Black",
    "Red",
    "White",
    "Blue",
    "Grey",
    "Mystic Black",
    "Crystal Black",
    "Orange",
    "Silver",
    "Gold",
    "Yellow",
    "Brown",
    "Pink",
    "Purple",
    "Cream",
    "Dark Gray",
    "Midnight Black",
    "Titanium Silver",
    "Starry Black",
    "Mint Green",
    "Sunrise Gold",
    "Carbon Black",
    "Flowing Silver",
    "Sea Blue",
    "Graphite",
    "Space Black",
    "Navy",
    "Lavender",
    "Titanium",
    "Misty Pink",
    "Ice Blue",
    "Navy Blue",
    "Sky Silver",
    "Ocean Blue",
    "Light Green",
    "Moonlight White",
    "Titanium Violet",
    "Titanium Gray",
    "Titanium Blue",
    "Titanium Black",
    "Cobalt Violet",
    "Amber Yellow",
    "Natural Titanium",
    "White Titanium",
    "Starlight",
    "Sierra Blue",
    "Space Gray",
    "Iron Gray",
    "Midnight",
    "Cyclone Black",
    "Waving Aqua",
    "Voyager Black",
    "Razor Green",
    "Silver Shadow",
    "Mint",
    "Charcoal",
    "Stainless Steel",
    "Isle Blue",
    "Dark Green",
    "Lavender Purple",
    "Desert Gold",
    "Sandy Gold",
    "Ultramarine",
    "Desert Titanium",
    "Silver Frost",
    "Ocean Cyan",
    "Jet Black",
    "Monet Gold",
    "Deep Purple",
    "Icy Blue",
    "Midnight Green",
    "Luminous Blue",
    "Skyline Blue",
    "Pearl White",
    "Plume White",
    "Awesome Navy",
    "Awesome White",
    "Suede Gray",
    "Suede Grey",
    "Awesome Light Gray",
    "Meteor Silver",
    "Luna Grey",
    "Sky Blue",
    "Mercurial Silver",
    "Cosmic Orange",
    "Luminous Green",
    "Pantone Amazonite",
    "Pantone Slipstream",
    "Phantom Black",
    "Phantom Green",
    "Phantom Silver",
    "Violet",
    "Light Violet",
    "Green",
    "Metallic Blue",
    "Mystic Bronze",
  ],
};

// Price boundaries
export const MIN_PRICE = 1380;
export const MAX_PRICE = 199000;

// Color mapping for visual display
export const colorMap = {
  black: "#000000",
  red: "#FF0000",
  white: "#FFFFFF",
  blue: "#0000FF",
  grey: "#808080",
  gray: "#808080",
  "mystic black": "#0A0A0A",
  "crystal black": "#1A1A1A",
  orange: "#FFA500",
  silver: "#C0C0C0",
  gold: "#FFD700",
  yellow: "#FFFF00",
  brown: "#8B4513",
  pink: "#FFC0CB",
  purple: "#800080",
  cream: "#FFFDD0",
  "dark gray": "#A9A9A9",
  "midnight black": "#000000",
  "titanium silver": "#C9CACB",
  "starry black": "#0D0D0D",
  "mint green": "#98FF98",
  "sunrise gold": "#F2C572",
  "carbon black": "#050505",
  "flowing silver": "#D5D5D5",
  "sea blue": "#1E90FF",
  graphite: "#4B4B4B",
  "space black": "#121212",
  navy: "#000080",
  lavender: "#E6E6FA",
  titanium: "#878787",
  "misty pink": "#F6D1D1",
  "ice blue": "#AFDBF5",
  "navy blue": "#000080",
  "sky silver": "#D0D4D8",
  "ocean blue": "#0066CC",
  "light green": "#90EE90",
  "moonlight white": "#F8F8F8",
  "titanium violet": "#7F6A93",
  "titanium gray": "#A1A1A1",
  "titanium blue": "#3A6EA5",
  "titanium black": "#0F0F0F",
  "cobalt violet": "#8A2BE2",
  "amber yellow": "#FFBF00",
  "natural titanium": "#8B8682",
  "white titanium": "#EAEAEA",
  starlight: "#F5F1E5",
  "sierra blue": "#A8C4E5",
  "space gray": "#4A4A4A",
  "iron gray": "#6E6E6E",
  midnight: "#191970",
  "cyclone black": "#0C0C0C",
  "waving aqua": "#66D4CF",
  "voyager black": "#0B0B0B",
  "razor green": "#4CAF50",
  "silver shadow": "#D3D3D3",
  mint: "#AAF0D1",
  charcoal: "#36454F",
  "stainless steel": "#CED0CE",
  "isle blue": "#3B6BA5",
  "dark green": "#006400",
  "lavender purple": "#B57EDC",
  "desert gold": "#CFAE70",
  "sandy gold": "#D4BC8A",
  ultramarine: "#3F00FF",
  "desert titanium": "#8E8B82",
  "silver frost": "#D8DDE3",
  "ocean cyan": "#2BC7BE",
  "jet black": "#0A0A0A",
  "monet gold": "#E2C26F",
  "deep purple": "#4B0082",
  "icy blue": "#B7DFF7",
  "midnight green": "#004953",
  "luminous blue": "#4A90E2",
  "skyline blue": "#7BB7E5",
  "pearl white": "#F9F6EE",
  "plume white": "#FAFAF0",
  "awesome navy": "#1B2A41",
  "awesome white": "#FDFDFD",
  "awesome light gray": "#D3D3D3",
  "suede gray": "#8A8A8A",
  "suede grey": "#8A8A8A",
  "meteor silver": "#CACACA",
  "luna grey": "#AEB2B5",
  "sky blue": "#87CEEB",
  "mercurial silver": "#D0D0D0",
  "cosmic orange": "#FF6F3C",
  "luminous green": "#32CD32",
  "pantone amazonite": "#00A99D",
  "pantone slipstream": "#7A99AC",
  "phantom black": "#000000",
  "phantom green": "#2D5016",
  "phantom silver": "#C0C0C0",
  violet: "#EE82EE",
  "light violet": "#D6A2E8",
  green: "#008000",
  "metallic blue": "#325C9E",
  "mystic bronze": "#CD7F32",
};
